### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character '\ufeff' in position 0

### ISSUE THREAD

**Issue by cheyuans** [llSourcell/twitter_sentiment_challenge#3]
When i run QGIS for geocoding CVS with google, an error came out.

Does anyone can help me with this?

The full decription shown below:

"""An error has occurred while executing Python code: 

UnicodeEncodeError: 'charmap' codec can't encode character '\ufeff' in position 0: character maps to 
Traceback (most recent call last):
  File "C:/Users/Cheyu/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\mmqgis\mmqgis_dialogs.py", line 1199, in run
    shapefilename, notfoundfile, fields, service, apikey, 1)
  File "C:/Users/Cheyu/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\mmqgis\mmqgis_library.py", line 2005, in mmqgis_geocode_web_service
    notwriter.writerow(header)
  File "E:\OSGeo4W64\apps\Python36\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\ufeff' in position 0: character maps to 

Python version: 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] 
QGIS version: 3.2.0-Bonn Bonn, bc43194061 

Python Path:
E:/OSGeo4W64/apps/qgis/./python
C:/Users/Cheyu/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Cheyu/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
E:/OSGeo4W64/apps/qgis/./python/plugins
E:\OSGeo4W64\bin\python36.zip
E:\OSGeo4W64\apps\Python36\DLLs
E:\OSGeo4W64\apps\Python36\lib
E:\OSGeo4W64\bin
E:\OSGeo4W64\apps\Python36
E:\OSGeo4W64\apps\Python36\lib\site-packages
E:\OSGeo4W64\apps\Python36\lib\site-packages\h5py-2.7.0-py3.6-win-amd64.egg
E:\OSGeo4W64\apps\Python36\lib\site-packages\win32
E:\OSGeo4W64\apps\Python36\lib\site-packages\win32\lib
E:\OSGeo4W64\apps\Python36\lib\site-packages\Pythonwin
C:/Users/Cheyu/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\Cheyu\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms
"""

**Comment by khoeftbe** [comment]
Hi! I have the same problem. Have you found a solution yet?
